name: Cache shell dependencies

on:
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cachix use earnestresearch-public
    - run: nix-build ./default.nix -A okta-aws-login.components.exes.okta-aws-login
    - run: nix-shell --run "exit 0"
