name: CD Linux

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: okta-aws-login-Linux-x86_64
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: $(nix-build --no-link -A fullBuildScript) > output
      - run: cp -v $(cat output)/bin/okta-aws-login ./okta-aws-login-Linux-x86_64
