name: PR builds

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
        enable-stack: true
        stack-version: 'latest'
    - uses: actions/cache@v2
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml', '**/stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ env.cache-name }}-
    - run: stack --system-ghc test
