name: Build

on: [push]

jobs:
  tests:
    if: startsWith(github.ref, 'refs/heads/') && (github.ref != 'refs/heads/main')
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v3
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml', '**/stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ env.cache-name }}-
      - run: stack --system-ghc test
  linux-binary:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: static-haskell-nix
      - run: $(nix-build --no-link -A fullBuildScript) > output
      - run: cp -v $(cat output)/bin/okta-aws-login ./okta-aws-login-Linux-x86_64
      - uses: softprops/action-gh-release@v0.1.7
        with:
          files: okta-aws-login-Linux-x86_64
  macos-binary:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v3
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml', '**/stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ env.cache-name }}-
      - run: stack --system-ghc --local-bin-path . install
      - run: otool -L okta-aws-login
      - run: mv -v okta-aws-login ./okta-aws-login-MacOS-x86_64
      - uses: softprops/action-gh-release@v0.1.7
        with:
          files: okta-aws-login-MacOS-x86_64
