name: PR builds

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v6
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cachix use earnestresearch-public
    - run: nix-shell ./shell.nix --run "pre-commit run --all-files --show-diff-on-failure --color never"
    - run: nix-build ./shell.nix -A okta-aws-login-tests
