name: PR builds

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: earnestresearch-public
        signingKey: '${{ secrets.EARNESTRESEARCH_PUBLIC_CACHIX_SIGNING_KEY }}'
    - run: cachix use earnestresearch-public
    - run: nix-build -A okta-aws-login.components.exes
    - run: ./result/bin/okta-aws-login --help
    - run: nix-shell ./shell.nix --run "pre-commit run --all-files --show-diff-on-failure --color never"
    - run: nix-build ./shell.nix -A okta-aws-login-tests
